Move pkgdest to /var/pkgdest
chaotic-aur/toolbox pull request #10
Opened 2020-12-29 23:42 UTC by PedroHLC

* Move PKGDEST from `"~/pkgdest"` to `"/var/pkgdest"` -- This way it won't be caught in the home's `chown -R`.
* Change default CAUR_OVERLAY_TYPE to `kernel`;
* Readd `set -euo pipefail` that was miss-removed;
* Do linter complains.

2020-12-29 23:56 UTC, thotypous commented
need to `chown main-builder:main-builder /var/pkgdest` inside the container, otherwise main-builder will not be able to write to it

2020-12-29 23:56 UTC, thotypous requested changes
need to `chown main-builder:main-builder /var/pkgdest` inside the container, otherwise main-builder will not be able to write to it

2020-12-30 00:00 UTC, PedroHLC commented
> need to chown main-builder:main-builder /var/pkgdest inside the container, otherwise main-builder will not be able to write to it

Not true, overlayfs depends on the upper directory permission for that...

2020-12-30 00:46 UTC, thotypous approved these changes

2020-12-30 00:46 UTC, merged